### PR TITLE
Added splash screen

### PR DESCRIPTION
**Pull request by heyprincesingh**
#3  Added a customized splash screen of 3 sec everytime user will open the application.
Check it out and if any improvement needed, let me know.
Else consider merging my pull request.

Thank you!!🎉🎉

### CODE REVIEW

**Comment by heyprincesingh** [comment]
@cynthiakonar hey! can you please have a look at this PR, and tell me if need any changes.

**Comment by cynthiakonar** [comment]
Great work 💜 
Can you add this screenshot to the readme as well?

**Comment by heyprincesingh** [comment]
> Great work 💜 Can you add this screenshot to the readme as well?

Yeah definitely!

**Comment by cynthiakonar** [comment]
All good! I will be merging the PR. 
Thank you!

**Comment by heyprincesingh** [comment]
@cynthiakonar
Thank you!!

**Pull request merged**
